interface global {
	checkboxes:NodeListOf<HTMLInputElement> 
	profileSelector:NodeListOf<HTMLSelectElement> 
	accountSelectors:NodeListOf<HTMLSelectElement> 
	countrySelectors:NodeListOf<HTMLSelectElement> 
	proxyListSelectors:NodeListOf<HTMLSelectElement> 
	siteSelectors:NodeListOf<HTMLSelectElement> 
	navigationSelectors:NodeListOf<HTMLElement> 
	reloadBtn:any 
	minimizeBtn:any 
	closeBtn:any 
	tasksHeader:any 
	importTaskBtn:HTMLButtonElement 
	exportTaskBtn:HTMLButtonElement 
	globalMonitorDelay:any 
	globalErrorDelay:any 
	globalTimeoutDelay:any 
	taskTable:any 
	taskTableBody:any 
	runAllBtn:any 
	stopAllBtn:any 
	clearTasksBtn:any 
	newTask_Site:any 
	newTask_Profile:any 
	newTask_Mode:any 
	newTask_RestockMode:any 
	newTask_CheckoutAttempts:any 
	newTask_Quantity:any 
	newTask_CartDelay:any 
	newTask_CheckoutDelay:any 
	newTask_MonitorDelay:any 
	newTask_ErrorDelay:any 
	newTask_Timeout:any 
	newTask_ProxyList:any 
	newTask_PriceLimit:any 
	newTask_StartDate:any 
	newTask_StartTime:any 
	newTask_Restocks:any 
	newTask_SkipCaptcha:any 
	newTask_threeD:any 
	newTask_products:any 
	newTask_styles:any 
	newTask_sizes:any 
	newTask_SearchInput:any 
	newTask_Category:any 
	newTask_Size:any 
	newTask_Style:any 
	newTask_ProductQty:any 
	newTask_saveBtn:any 
	profilesWrapper:any 
	billingFirst:any 
	billingLast:any 
	billingEmail:any 
	billingTelephone:any 
	billingAddress1:any 
	billingAddress2:any 
	billingCity:any 
	billingZip:any 
	billingCountry:any 
	billingState:any 
	useSameShippingAddress:any 
	shippingFirst:any 
	shippingLast:any 
	shippingEmail:any 
	shippingTelephone:any 
	shippingAddress1:any 
	shippingAddress2:any 
	shippingCity:any 
	shippingZip:any 
	shippingCountry:any 
	shippingState:any 
	paymentType:any 
	cardNumber:any 
	cardExpiryMonth:any 
	cardExpiryYear:any 
	cardCvv:any 
	_profileId:any 
	profileName:any 
	saveProfileBtn:any 
	profileLoader:any 
	importProfileBtn:any 
	exportProfileBtn:any 
	deleteProfileBtn:any 
	clearProfilesBtn:any 
	profileElements:any 
	importProxyBtn:any 
	exportProxyBtn:any 
	proxyHeader:any 
	proxyListName:any 
	massProxyInput:any 
	saveProxyList:any 
	proxyListSelectorMain:any 
	proxyTableName:any 
	proxyTestSite:any 
	proxyTestTable:any 
	proxyTestAll:any 
	proxyDeleteList:any 
	harverster_Name:any 
	harvester_SaveBtn:any 
	harvesterTable:any 
	harvester_ClearBtn:any 
	orderTableBody:any 
	clearAnalyticsBtn:any 
	monitorProxyList:any 
	currentBrowserPath:any 
	installBrowserBtn:any 
	resetBtn:any 
	signoutBtn:any 
	customDiscord:any 
	testDiscordBtn:any 
	version:any 
}